# Generated by Django 3.0.5 on 2020-04-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_preference_and_settings',
            name='finance',
            field=models.CharField(choices=[('000', '000'), ('001', '001'), ('010', '010'), ('100', '100'), ('011', '011'), ('101', '101'), ('110', '110'), ('111', '111')], default='010', max_length=3),
        ),
        migrations.AlterField(
            model_name='user_preference_and_settings',
            name='service_appointments',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=2),
        ),
        migrations.AlterField(
            model_name='user_preference_and_settings',
            name='smart_car_care',
            field=models.CharField(choices=[('000', '000'), ('001', '001'), ('010', '010'), ('100', '100'), ('011', '011'), ('101', '101'), ('110', '110'), ('111', '111')], default='010', max_length=3),
        ),
        migrations.AlterField(
            model_name='user_preference_and_settings',
            name='smart_home_care',
            field=models.CharField(choices=[('000', '000'), ('001', '001'), ('010', '010'), ('100', '100'), ('011', '011'), ('101', '101'), ('110', '110'), ('111', '111')], default='010', max_length=3),
        ),
        migrations.AlterField(
            model_name='user_preference_and_settings',
            name='vacation_planning',
            field=models.CharField(choices=[('000', '000'), ('001', '001'), ('010', '010'), ('100', '100'), ('011', '011'), ('101', '101'), ('110', '110'), ('111', '111')], default='010', max_length=3),
        ),
    ]
